### ISSUE TITLE
no image found

### ISSUE THREAD

**Issue by shehuimao** [lucasjinreal/alfred#15]
when i use 'alfred vocview -i JPEGImages/ -l Annotations/' in my pic  catalog，it appears 
**Alfred - Valet of Artificial Intelligence.
Author: Lucas Jin
At    : 20202.10.01, since 2019.11.11
Loc   : Shenzhen, China
Star  : http://github.com/jinfagang/alfred
Ver.  : 2.7.1

=> Module: data
=> Action: vocview
INFO 08.19 01:53:30 view_voc.py:58: img root: JPEGImages/, label root: Annotations/
INFO 08.19 01:53:30 view_voc.py:61: label major will using xmls to found images... it might cause no image found
: cannot connect to X server
**

**Comment by jinfagang** [comment]
@shehuimao You can open window on server. You probably better run this on your local PC rather than server.
