### ISSUE TITLE
ImportError: cannot import name 'device'

### ISSUE THREAD

**Issue by Ghustwb** [lucasjinreal/alfred#27]
I got this issue when run alfred

**Comment by jinfagang** [comment]
upgrade to the latest version

**Comment by Ghustwb** [comment]
how to upgrade latest version ? I installed it by "sudo pip3 isntall alfred-py"

**Comment by jinfagang** [comment]
@Ghustwb  `pip install -U alfred-py` or install master version from github

**Comment by Younger6163** [comment]
> @Ghustwb `pip install -U alfred-py` or install master version from github
I used the "`pip install -U alfred-py`" command, but I still get the same error.

**Comment by jinfagang** [comment]
The latest one shouldn't occur this, if it does, make sure old alfred-py uninstalled,

try `alfred -v` verify
