### ISSUE TITLE
shape_predictor_68_face_landmarks.dat not fund.

### ISSUE THREAD

**Issue by JiangKui007** [lucasjinreal/alfred#9]
Alfred - Valet of Artificial Intelligence.
Author: Lucas Jin
At    : 20202.10.01, since 2019.11.11
Loc   : Shenzhen, China
Star  : http://github.com/jinfagang/alfred
Ver.  : 2.7.1

=> Module: vision
=> Action: getface
Extract faces from ../data
Traceback (most recent call last):
  File "/Users/MRJ/anaconda3/envs/python37/lib/python3.7/site-packages/alfred/alfred.py", line 256, in main
    face_extractor = FaceExtractor()
  File "/Users/MRJ/anaconda3/envs/python37/lib/python3.7/site-packages/alfred/modules/vision/face_extractor.py", line 46, in __init__
    self.predictor = dlib.shape_predictor(predictor_path)
RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat
 parse args error, type -h to see help. msg: Unable to open shape_predictor_68_face_landmarks.dat

**Comment by jinfagang** [comment]
You gonna need dlib installed and download it's face model weights.

**Comment by JiangKui007** [comment]
> You gonna need dlib installed and download it's face model weights if you using face related module.

dlib                               19.19.0
